# Copyright (c) Microsoft. All rights reserved.

"""E2E contract test for Section 2.B: readiness commands and /root/.local/bin.

Profiles generated by ``amplifier-bundle-amplifier-tester``'s
``setup-digital-twin`` agent currently wrap every ``amplifier`` invocation in
an inline ``export PATH="/root/.local/bin:$PATH"`` prefix, including in
``readiness.command``. The seven prefix sites in
``agents/setup-digital-twin.md`` exist as a workaround for the fact that
``readiness._run_command_check`` runs commands via ``bash -c`` (non-login,
non-interactive), which does not source ``/etc/profile.d/dtu-env.sh`` where
DTU writes the baseline ``/root/.cargo/bin:/root/.local/bin`` PATH addition.

Contract this test asserts: a profile that installs a binary into
``/root/.local/bin`` (the directory ``uv tool install`` uses for the
``amplifier`` CLI) should be able to invoke that binary directly from
``readiness.command`` without an inline PATH prefix. The tester agent should
not need to know about PATH; once a binary is installed where DTU's
``/etc/profile.d/dtu-env.sh`` already advertises it, every code path that DTU
runs commands through should be able to find it.

The test FAILS today because ``bash -c <cmd>`` (readiness) does not source
``/etc/profile.d/*.sh``. setup_cmds, by contrast, runs via ``bash -lc`` and
does source profile.d, so the install verification succeeds -- isolating the
failure to the readiness layer.

Fix candidates (DTU-side, in priority order):
- Change ``readiness._run_command_check`` to use ``bash -lc`` (matches the
  semantics already used by setup_cmds and the default ``exec``).
- Write ``/root/.cargo/bin:/root/.local/bin`` into ``/etc/environment`` so
  non-login shells see it too.

After the DTU fix lands, ``amplifier-bundle-amplifier-tester`` can drop the
seven inline ``export PATH=...`` prefix sites in ``setup-digital-twin.md``.

Run with: uv run pytest tests/e2e/features/test_amplifier_tester_path.py --run-e2e -v -s
"""

import pytest

from conftest import register_dtu_instance
from helpers import run_cli, run_cli_json


@pytest.fixture(scope="module")
def tester_style_path_profile(tmp_path_factory):
    """Tester-style profile that installs uv into /root/.local/bin and uses a
    bare readiness command (no inline PATH prefix).

    Mirrors what an amplifier-tester-generated profile would look like *after*
    the Section 2.B fix lands -- setup_cmds and readiness both invoke the
    installed binary directly, trusting that /etc/profile.d/dtu-env.sh makes
    it discoverable everywhere DTU runs commands.

    Uses ``uv`` (very fast install, ~3s) rather than full Amplifier (~60s) to
    keep the test cheap. The failure mode is identical: both binaries live in
    /root/.local/bin and need the same PATH plumbing.
    """
    profile_dir = tmp_path_factory.mktemp("tester-path-profile")
    profile_path = profile_dir / "amplifier-tester-path-contract.yaml"
    profile_path.write_text(
        """\
name: amplifier-tester-path-contract
description: >
  Section 2.B contract: a binary installed to /root/.local/bin must be
  reachable from readiness.command without an inline `export PATH=...`
  workaround. Mirrors the structure of amplifier-tester-generated profiles.

base:
  image: ubuntu:24.04

provision:
  setup_cmds:
    - apt-get update && apt-get install -y curl
    # Install uv into /root/.local/bin -- same place uv tool install puts amplifier.
    - curl -LsSf https://astral.sh/uv/install.sh | sh
    # setup_cmds run via `bash -lc` (login shell -> sources /etc/profile.d/*),
    # so this works today even without an inline PATH prefix.
    - uv --version

readiness:
  # readiness commands run via `bash -c` (non-login, non-interactive -> does
  # NOT source /etc/profile.d/*). Currently fails because /root/.local/bin
  # is not on the default PATH. The tester agent works around this with an
  # inline `PATH=/root/.local/bin:$PATH` prefix; this test asserts the
  # workaround should not be necessary.
  - name: uv-on-readiness-path
    command: uv --version
"""
    )
    return str(profile_path)


@pytest.fixture(scope="module")
def dtu_env(tester_style_path_profile):
    """Launch the contract profile. ``launch`` may report readiness as failing
    but should still return a usable instance handle; if it errors entirely we
    still want the instance cleaned up.
    """
    result = run_cli("launch", tester_style_path_profile, timeout=180)
    # Parse whatever JSON came back so we can register for cleanup, even on
    # the failing-readiness path.
    import json

    data = {}
    try:
        data = json.loads(result.stdout)
    except (json.JSONDecodeError, ValueError):
        pass
    if isinstance(data, dict) and "id" in data:
        register_dtu_instance(data["id"])
    assert result.returncode == 0, (
        f"launch failed before reaching readiness:\n"
        f"  stdout: {result.stdout}\n"
        f"  stderr: {result.stderr}"
    )
    yield data
    if data.get("id"):
        run_cli("destroy", data["id"], timeout=30)


@pytest.mark.e2e
def test_setup_cmds_login_shell_sees_local_bin(dtu_env):
    """Baseline: setup_cmds run via `bash -lc` and DO source /etc/profile.d.

    This sanity check confirms the install succeeded and that the failure in
    the readiness test below is specifically attributable to readiness's shell
    invocation, not to a missing or broken binary.
    """
    result, _ = run_cli_json(
        "exec", dtu_env["id"], "--", "bash", "-lc", "uv --version", timeout=30
    )
    assert isinstance(result, dict), f"expected dict, got {type(result)}"
    assert result["exit_code"] == 0, (
        f"sanity check failed -- uv missing from login shell PATH. "
        f"Stdout: {result['stdout']!r} stderr: {result['stderr']!r}"
    )
    assert "uv " in result["stdout"], f"unexpected stdout: {result['stdout']!r}"


@pytest.mark.e2e
def test_readiness_command_works_without_inline_path_prefix(dtu_env):
    """Section 2.B contract: readiness.command should find /root/.local/bin
    binaries without the tester agent prepending `PATH=/root/.local/bin:$PATH`.

    FAILS today because ``readiness._run_command_check`` invokes the command
    via ``bash -c`` (non-login, non-interactive), which does not source
    ``/etc/profile.d/dtu-env.sh`` where DTU writes the baseline PATH addition.

    The fix can land in either bundle:
    - DTU: switch readiness to ``bash -lc`` (matches setup_cmds) OR write
      ``/etc/environment`` with the cargo/local bin paths.
    - amplifier-tester: keep the inline prefix until the DTU fix arrives.

    The expected post-fix behavior is what this test asserts: bare
    ``uv --version`` works from a readiness check on a profile that installed
    uv into ``/root/.local/bin``.
    """
    result, _ = run_cli_json("check-readiness", dtu_env["id"], timeout=60)
    assert isinstance(result, dict), f"expected dict, got {type(result)}"
    assert result.get("ready") is True, (
        "readiness command 'uv --version' (no inline PATH prefix) failed.\n"
        "This is the Section 2.B contract: a binary installed to "
        "/root/.local/bin should be reachable from readiness.command without\n"
        "the tester agent spraying `export PATH=/root/.local/bin:$PATH` at "
        "every site.\n"
        f"Result: {result}"
    )
